project_id = "jujgbkdamkjabjuerqxt"

[functions.generate-campaign]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.generate-ad-mockup]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.ai-support-chat]
verify_jwt = true

[functions.import-eventbrite-events]
verify_jwt = true
