/**
 * Utility functions for image optimization
 */

/**
 * Generate WebP fallback URLs for images
 * In production, these would be generated by a build process or CDN
 */
export function getOptimizedImageUrl(src: string, width?: number): string {
  // For now, return the original source
  // In production, this would return optimized versions
  if (width) {
    // This could integrate with a CDN that generates optimized images
    // For example: `${CDN_URL}/${src}?w=${width}&format=webp`
    return src;
  }
  return src;
}

/**
 * Generate srcset for responsive images
 */
export function generateSrcSet(src: string, widths: number[] = [640, 768, 1024, 1280, 1536]): string {
  return widths
    .map(width => `${getOptimizedImageUrl(src, width)} ${width}w`)
    .join(', ');
}

/**
 * Generate sizes attribute for responsive images
 */
export function generateSizes(breakpoints?: Record<string, string>): string {
  if (breakpoints) {
    return Object.entries(breakpoints)
      .map(([bp, size]) => `(max-width: ${bp}) ${size}`)
      .join(', ');
  }
  
  // Default responsive sizes
  return '(max-width: 640px) 100vw, (max-width: 1024px) 80vw, 1200px';
}

/**
 * Check if browser supports WebP
 */
export function supportsWebP(): Promise<boolean> {
  return new Promise((resolve) => {
    const webP = new Image();
    webP.onload = webP.onerror = function () {
      resolve(webP.height === 2);
    };
    webP.src = 'data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACyAgCdASoCAAIALmk0mk0iIiIiIgBoSygABc6WWgAA/veff/0PP8bA//LwYAAA';
  });
}
